apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.service.name }}
  labels: {{ .Values.global.service.labels }}
spec:
  type: {{ .Values.global.service.type }}
  ports:
    - port: {{ .Values.global.service.ports.port }}
      targetPort: {{ .Values.global.service.ports.targetPort }}
      protocol: {{ .Values.global.service.ports.protocol }}
  selector: {{ .Values.global.service.selector }}